"""
Fine-tune TrOCR on the synthetic handwritten menu dataset.

This script is adapted specifically for the synthetic dataset generated by
dataset_generator/synthetic/generate_synthetic_dataset.py. The dataset
already has proper train/val/test splits based on style_id (to ensure no
handwriting style leaks between splits).

Key differences from train_trocr.py:
- Uses pre-defined splits from manifest.csv (no random splitting)
- Dataset paths are relative to dataset_generator/synthetic/dataset_synth/
- Optimized hyperparameters for synthetic data
- Includes test set evaluation after training

Usage:
    python train_synthetic.py --dataset_dir ../dataset_generator/synthetic/dataset_synth --output_model_dir ../models/trocr_menu_synth_v1

    Or with custom hyperparameters:
    python train_synthetic.py --dataset_dir ../dataset_generator/synthetic/dataset_synth --output_model_dir ../models/trocr_menu_synth_v1 --batch_size 16 --max_epochs 15 --lr 3e-5

Dataset info:
    - Total samples: ~4400
    - Train: ~3000 samples (70%)
    - Val: ~650 samples (15%) 
    - Test: ~670 samples (15%)
    - Field types: headers, names, prices
    - Style-disjoint splits (no handwriting identity leaks)
"""
import argparse
import csv
from pathlib import Path

import torch
from PIL import Image
from torch.utils.data import Dataset
from transformers import (
    TrOCRProcessor,
    VisionEncoderDecoderModel,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    EarlyStoppingCallback,
)


class SyntheticMenuDataset(Dataset):
    """Dataset for synthetic handwritten menu crops."""
    
    def __init__(self, rows, dataset_root: Path, processor, max_target_length=32):
        self.rows = rows
        self.dataset_root = dataset_root
        self.processor = processor
        self.max_target_length = max_target_length

    def __len__(self):
        return len(self.rows)

    def __getitem__(self, idx):
        row = self.rows[idx]
        # crop_path is relative to dataset_root (e.g., "crops/name_00023.png")
        image_path = self.dataset_root / row["crop_path"]
        
        try:
            image = Image.open(image_path).convert("RGB")
        except Exception as e:
            print(f"Warning: Could not load image {image_path}: {e}")
            # Return a blank image as fallback
            image = Image.new("RGB", (384, 384), color="white")
        
        pixel_values = self.processor(image, return_tensors="pt").pixel_values.squeeze(0)

        labels = self.processor.tokenizer(
            row["text"],
            padding="max_length",
            max_length=self.max_target_length,
            truncation=True,
        ).input_ids
        
        # Ignore pad tokens in the loss
        labels = [l if l != self.processor.tokenizer.pad_token_id else -100 for l in labels]
        return {"pixel_values": pixel_values, "labels": torch.tensor(labels)}


def load_manifest(manifest_path: Path, split: str):
    """Load rows for a specific split from manifest.csv."""
    with open(manifest_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    
    # Filter by split
    filtered = [r for r in rows if r["split"] == split]
    return filtered


def make_compute_metrics(processor):
    """Create metrics computation function for evaluation."""
    import evaluate
    cer_metric = evaluate.load("cer")
    wer_metric = evaluate.load("wer")

    def compute_metrics(pred):
        pred_ids = pred.predictions
        label_ids = pred.label_ids
        
        # Decode predictions
        pred_str = processor.batch_decode(pred_ids, skip_special_tokens=True)
        
        # Decode labels (replace -100 with pad token)
        label_ids[label_ids == -100] = processor.tokenizer.pad_token_id
        label_str = processor.batch_decode(label_ids, skip_special_tokens=True)
        
        cer = cer_metric.compute(predictions=pred_str, references=label_str)
        wer = wer_metric.compute(predictions=pred_str, references=label_str)
        
        return {"cer": cer, "wer": wer}

    return compute_metrics


def main():
    parser = argparse.ArgumentParser(
        description=__doc__, 
        formatter_class=argparse.RawDescriptionHelpFormatter
    )
    parser.add_argument(
        "--dataset_dir", 
        required=True, 
        help="Path to synthetic dataset directory (containing manifest.csv and crops/)"
    )
    parser.add_argument(
        "--base_checkpoint", 
        default="microsoft/trocr-base-handwritten",
        help="Base TrOCR model to fine-tune from"
    )
    parser.add_argument(
        "--output_model_dir", 
        required=True,
        help="Directory to save the fine-tuned model"
    )
    parser.add_argument(
        "--max_epochs", 
        type=int, 
        default=20,
        help="Maximum number of training epochs"
    )
    parser.add_argument(
        "--batch_size", 
        type=int, 
        default=16,
        help="Training and evaluation batch size"
    )
    parser.add_argument(
        "--gradient_accumulation_steps",
        type=int,
        default=2,
        help="Accumulate gradients over N steps to simulate larger batch"
    )
    parser.add_argument(
        "--lr", 
        type=float, 
        default=5e-5,
        help="Learning rate"
    )
    parser.add_argument(
        "--early_stopping_patience", 
        type=int, 
        default=4,
        help="Stop training if validation CER doesn't improve for N epochs"
    )
    parser.add_argument(
        "--eval_test", 
        action="store_true",
        help="Evaluate on test set after training"
    )
    args = parser.parse_args()

    dataset_dir = Path(args.dataset_dir)
    manifest_path = dataset_dir / "manifest.csv"
    
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest file not found: {manifest_path}")
    
    print("=" * 70)
    print("SYNTHETIC MENU DATASET - TrOCR FINE-TUNING")
    print("=" * 70)
    
    # Load splits
    print("\nLoading dataset splits...")
    train_rows = load_manifest(manifest_path, "train")
    val_rows = load_manifest(manifest_path, "val")
    test_rows = load_manifest(manifest_path, "test")
    
    print(f"  Train: {len(train_rows)} samples")
    print(f"  Val:   {len(val_rows)} samples")
    print(f"  Test:  {len(test_rows)} samples")
    print(f"  Total: {len(train_rows) + len(val_rows) + len(test_rows)} samples")
    
    if len(train_rows) == 0:
        raise SystemExit("No training samples found!")
    if len(val_rows) == 0:
        raise SystemExit("No validation samples found!")
    
    # Check device
    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"\nTraining device: {device}")
    if device == "cpu":
        print("⚠ WARNING: No GPU detected. Training will be very slow.")
        print("  Consider using Google Colab or a machine with CUDA GPU.")
    
    # Load model and processor
    print(f"\nLoading base model: {args.base_checkpoint}")
    processor = TrOCRProcessor.from_pretrained(args.base_checkpoint)
    model = VisionEncoderDecoderModel.from_pretrained(args.base_checkpoint).to(device)
    
    # Configure model for generation
    model.config.decoder_start_token_id = processor.tokenizer.cls_token_id
    model.config.pad_token_id = processor.tokenizer.pad_token_id
    model.config.vocab_size = model.config.decoder.vocab_size
    model.config.eos_token_id = processor.tokenizer.sep_token_id
    model.config.max_length = 32
    model.config.early_stopping = True
    model.config.no_repeat_ngram_size = 3
    model.config.length_penalty = 2.0
    model.config.num_beams = 4
    
    # Create datasets
    print("\nCreating datasets...")
    train_dataset = SyntheticMenuDataset(train_rows, dataset_dir, processor)
    val_dataset = SyntheticMenuDataset(val_rows, dataset_dir, processor)
    
    # Training arguments
    output_dir = Path(args.output_model_dir)
    
    # Optimize for RTX 3050 4GB - maximize throughput while staying within memory
    effective_batch_size = args.batch_size * args.gradient_accumulation_steps
    
    training_args = Seq2SeqTrainingArguments(
        output_dir=str(output_dir / "checkpoints"),
        predict_with_generate=True,
        eval_strategy="epoch",
        save_strategy="epoch",
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=args.batch_size * 2,  # Can use more for eval
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        num_train_epochs=args.max_epochs,
        learning_rate=args.lr,
        fp16=True,  # Always use mixed precision for speed
        fp16_full_eval=True,  # Use fp16 for evaluation too
        dataloader_num_workers=4,  # Parallel data loading
        dataloader_pin_memory=True,  # Faster GPU transfer
        logging_steps=20,
        logging_first_step=True,
        load_best_model_at_end=True,
        metric_for_best_model="cer",
        greater_is_better=False,
        save_total_limit=2,  # Keep only 2 checkpoints to save disk space
        report_to=[],
        warmup_steps=100,
        weight_decay=0.01,
        max_grad_norm=1.0,  # Gradient clipping for stability
        optim="adamw_torch",  # Use PyTorch's AdamW
        # Memory optimizations
        gradient_checkpointing=False,  # Disabled for speed (we have enough memory)
        ddp_find_unused_parameters=False,
    )
    
    print(f"\nOptimized for RTX 3050 4GB VRAM:")
    print(f"  Batch size per device: {args.batch_size}")
    print(f"  Gradient accumulation steps: {args.gradient_accumulation_steps}")
    print(f"  Effective batch size: {effective_batch_size}")
    print(f"  Mixed precision (FP16): Enabled")
    print(f"  Data loader workers: 4")
    
    # Create trainer
    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=make_compute_metrics(processor),
        callbacks=[EarlyStoppingCallback(early_stopping_patience=args.early_stopping_patience)],
    )
    
    # Train
    print("\n" + "=" * 70)
    print("STARTING TRAINING")
    print("=" * 70)
    print(f"Hyperparameters:")
    print(f"  Physical batch size: {args.batch_size}")
    print(f"  Gradient accumulation: {args.gradient_accumulation_steps}")
    print(f"  Effective batch size: {args.batch_size * args.gradient_accumulation_steps}")
    print(f"  Learning rate: {args.lr}")
    print(f"  Max epochs: {args.max_epochs}")
    print(f"  Early stopping patience: {args.early_stopping_patience}")
    print(f"  GPU: {torch.cuda.get_device_name(0)}")
    print(f"  CUDA memory allocated: {torch.cuda.memory_allocated(0) / 1024**2:.2f} MB")
    print()
    
    trainer.train()
    
    # Save final model
    print("\n" + "=" * 70)
    print("TRAINING COMPLETE - SAVING MODEL")
    print("=" * 70)
    
    output_dir.mkdir(parents=True, exist_ok=True)
    model.save_pretrained(output_dir)
    processor.save_pretrained(output_dir)
    
    print(f"\n✓ Model saved to: {output_dir}")
    
    # Evaluate on test set if requested
    if args.eval_test and len(test_rows) > 0:
        print("\n" + "=" * 70)
        print("EVALUATING ON TEST SET")
        print("=" * 70)
        
        test_dataset = SyntheticMenuDataset(test_rows, dataset_dir, processor)
        test_results = trainer.evaluate(test_dataset)
        
        print(f"\nTest set results:")
        print(f"  CER: {test_results.get('eval_cer', 'N/A'):.4f}")
        print(f"  WER: {test_results.get('eval_wer', 'N/A'):.4f}")
    
    # Usage instructions
    print("\n" + "=" * 70)
    print("NEXT STEPS")
    print("=" * 70)
    print("\n1. To use this model in your pipeline, update src/config.py:")
    print(f"""
    @dataclass
    class RecognitionConfig:
        model_checkpoint: str = r"{output_dir.absolute()}"
    """)
    
    print("\n2. Or load it programmatically:")
    print(f"""
    from src.config import Config
    config = Config()
    config.recognition.model_checkpoint = r"{output_dir.absolute()}"
    """)
    
    print("\n3. Evaluate with real photos before production:")
    print("   python training/evaluate.py --out_dir <real_photos_dataset> --model", output_dir)
    
    print("\n⚠ IMPORTANT: This model was trained on SYNTHETIC data.")
    print("   Performance on real handwritten menus may differ significantly.")
    print("   Always validate with real-world examples before deployment.")
    print()


if __name__ == "__main__":
    main()
