"""
Fine-tune TrOCR on the synthetic handwritten menu dataset.

Adapted for the dataset generated by generate_synthetic_dataset.py, which
already has style-disjoint train/val/test splits baked into manifest.csv
(see that script's docstring for why the split is style-disjoint but not
vocab-disjoint).

Usage:
    python train_synthetic.py --dataset_dir ../synthetic/dataset_synth --output_model_dir ../models/trocr_menu_synth_v1

    With custom hyperparameters:
    python train_synthetic.py --dataset_dir ../synthetic/dataset_synth --output_model_dir ../models/trocr_menu_synth_v1 --batch_size 2 --gradient_accumulation_steps 8 --max_epochs 15

A note on VRAM (RTX 3050 4GB and similar small cards):
    Full fine-tuning of TrOCR-base (~334M params) needs meaningfully more
    than 4GB even at batch size 1, once you count AdamW's optimizer state
    (roughly 4x parameter memory in fp32 by default) plus activations.
    This script defaults to a small batch size + gradient checkpointing +
    gradient accumulation to fit that budget. If you still hit
    `CUDA out of memory`, drop --batch_size to 1 before anything else -
    gradient_accumulation_steps can make up the effective batch size
    without costing VRAM.
"""
import argparse
import csv
from pathlib import Path

import torch
from PIL import Image
from torch.utils.data import Dataset
from transformers import (
    TrOCRProcessor,
    VisionEncoderDecoderModel,
    Seq2SeqTrainer,
    Seq2SeqTrainingArguments,
    EarlyStoppingCallback,
)


class SyntheticMenuDataset(Dataset):
    """Dataset for synthetic handwritten menu crops.

    Tracks and reports missing/unreadable images instead of silently
    substituting a blank placeholder while keeping the real text label -
    a blank-image-to-real-text pair is label noise, not a safe fallback,
    and would otherwise train the model on garbage without any signal
    that it happened.
    """

    def __init__(self, rows, dataset_root: Path, processor, max_target_length=32, split_name="dataset"):
        self.dataset_root = dataset_root
        self.processor = processor
        self.max_target_length = max_target_length
        self.split_name = split_name

        self.rows = []
        missing = []
        for row in rows:
            if (dataset_root / row["crop_path"]).exists():
                self.rows.append(row)
            else:
                missing.append(row["crop_path"])

        if missing:
            print(
                f"WARNING [{split_name}]: {len(missing)}/{len(rows)} crops referenced in "
                f"manifest.csv could not be found on disk and were EXCLUDED (not silently "
                f"replaced with a blank image). First few: {missing[:5]}"
            )

    def __len__(self):
        return len(self.rows)

    def __getitem__(self, idx):
        row = self.rows[idx]
        image_path = self.dataset_root / row["crop_path"]
        image = Image.open(image_path).convert("RGB")  # already verified to exist in __init__

        pixel_values = self.processor(image, return_tensors="pt").pixel_values.squeeze(0)

        labels = self.processor.tokenizer(
            row["text"],
            padding="max_length",
            max_length=self.max_target_length,
            truncation=True,
        ).input_ids
        labels = [l if l != self.processor.tokenizer.pad_token_id else -100 for l in labels]
        return {"pixel_values": pixel_values, "labels": torch.tensor(labels)}


def load_manifest(manifest_path: Path, split: str):
    with open(manifest_path, newline="", encoding="utf-8") as f:
        rows = list(csv.DictReader(f))
    return [r for r in rows if r["split"] == split]


def make_compute_metrics(processor):
    # Imported from the pip package `evaluate`, NOT this project's own
    # training/evaluate.py script. If this file ever lives in the same
    # folder as that script, Python's sys.path[0] (the running script's
    # own directory) will shadow the pip package and this import breaks
    # with a confusing ImportError. Keep them in separate folders.
    import evaluate as hf_evaluate
    cer_metric = hf_evaluate.load("cer")
    wer_metric = hf_evaluate.load("wer")

    def compute_metrics(pred):
        pred_ids = pred.predictions
        label_ids = pred.label_ids

        pred_str = processor.batch_decode(pred_ids, skip_special_tokens=True)
        label_ids[label_ids == -100] = processor.tokenizer.pad_token_id
        label_str = processor.batch_decode(label_ids, skip_special_tokens=True)

        cer = cer_metric.compute(predictions=pred_str, references=label_str)
        wer = wer_metric.compute(predictions=pred_str, references=label_str)
        return {"cer": cer, "wer": wer}

    return compute_metrics


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--dataset_dir", required=True, help="Path to synthetic dataset dir (containing manifest.csv and crops/)")
    parser.add_argument("--base_checkpoint", default="microsoft/trocr-base-handwritten")
    parser.add_argument("--output_model_dir", required=True)
    parser.add_argument("--max_epochs", type=int, default=20)
    parser.add_argument("--batch_size", type=int, default=2,
                         help="Small default on purpose - see the VRAM note in this script's docstring")
    parser.add_argument("--gradient_accumulation_steps", type=int, default=8,
                         help="Effective batch size = batch_size * this, without the VRAM cost of a literally bigger batch")
    parser.add_argument("--lr", type=float, default=5e-5)
    parser.add_argument("--early_stopping_patience", type=int, default=4)
    parser.add_argument("--eval_test", action="store_true", help="Evaluate on test set after training")
    parser.add_argument("--no_gradient_checkpointing", action="store_true",
                         help="Disable gradient checkpointing (only if you have plenty of VRAM to spare - it trades compute for memory)")
    args = parser.parse_args()

    dataset_dir = Path(args.dataset_dir).resolve()
    manifest_path = dataset_dir / "manifest.csv"
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest file not found: {manifest_path}")

    print("=" * 70)
    print("SYNTHETIC MENU DATASET - TrOCR FINE-TUNING")
    print("=" * 70)

    print("\nLoading dataset splits...")
    train_rows = load_manifest(manifest_path, "train")
    val_rows = load_manifest(manifest_path, "val")
    test_rows = load_manifest(manifest_path, "test")
    print(f"  Train: {len(train_rows)} samples")
    print(f"  Val:   {len(val_rows)} samples")
    print(f"  Test:  {len(test_rows)} samples")

    if len(train_rows) == 0:
        raise SystemExit("No training samples found!")
    if len(val_rows) == 0:
        raise SystemExit("No validation samples found!")

    device = "cuda" if torch.cuda.is_available() else "cpu"
    print(f"\nTraining device: {device}")
    if device == "cpu":
        print("WARNING: No GPU detected. Training will be very slow - consider Colab or a CUDA machine.")
    else:
        print(f"  GPU: {torch.cuda.get_device_name(0)}")

    print(f"\nLoading base model: {args.base_checkpoint}")
    processor = TrOCRProcessor.from_pretrained(args.base_checkpoint)
    model = VisionEncoderDecoderModel.from_pretrained(args.base_checkpoint).to(device)

    model.config.decoder_start_token_id = processor.tokenizer.cls_token_id
    model.config.pad_token_id = processor.tokenizer.pad_token_id
    model.config.vocab_size = model.config.decoder.vocab_size
    model.config.eos_token_id = processor.tokenizer.sep_token_id
    model.config.max_length = 32
    model.config.early_stopping = True
    model.config.no_repeat_ngram_size = 3
    model.config.length_penalty = 2.0
    model.config.num_beams = 4

    print("\nCreating datasets...")
    train_dataset = SyntheticMenuDataset(train_rows, dataset_dir, processor, split_name="train")
    val_dataset = SyntheticMenuDataset(val_rows, dataset_dir, processor, split_name="val")

    output_dir = Path(args.output_model_dir)
    effective_batch_size = args.batch_size * args.gradient_accumulation_steps
    use_fp16 = device == "cuda"
    use_gradient_checkpointing = device == "cuda" and not args.no_gradient_checkpointing

    training_args = Seq2SeqTrainingArguments(
        output_dir=str(output_dir / "checkpoints"),
        predict_with_generate=True,
        eval_strategy="epoch",
        save_strategy="epoch",
        per_device_train_batch_size=args.batch_size,
        per_device_eval_batch_size=max(1, args.batch_size),  # keep eval batch modest too - it also costs VRAM
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        num_train_epochs=args.max_epochs,
        learning_rate=args.lr,
        fp16=use_fp16,
        fp16_full_eval=use_fp16,
        dataloader_num_workers=0,       # avoids a common Windows multiprocessing slowdown
        dataloader_pin_memory=False,    # ditto
        logging_steps=20,
        logging_first_step=True,
        load_best_model_at_end=True,
        metric_for_best_model="cer",
        greater_is_better=False,
        save_total_limit=2,
        report_to=[],
        warmup_steps=100,
        weight_decay=0.01,
        max_grad_norm=1.0,
        optim="adamw_torch",
        gradient_checkpointing=use_gradient_checkpointing,
        ddp_find_unused_parameters=False,
    )

    print(f"\nHyperparameters:")
    print(f"  Physical batch size: {args.batch_size}")
    print(f"  Gradient accumulation steps: {args.gradient_accumulation_steps}")
    print(f"  Effective batch size: {effective_batch_size}")
    print(f"  Mixed precision (FP16): {use_fp16}")
    print(f"  Gradient checkpointing: {use_gradient_checkpointing}")
    print(f"  Learning rate: {args.lr}")
    print(f"  Max epochs: {args.max_epochs}")
    print(f"  Early stopping patience: {args.early_stopping_patience}")

    trainer = Seq2SeqTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        compute_metrics=make_compute_metrics(processor),
        callbacks=[EarlyStoppingCallback(early_stopping_patience=args.early_stopping_patience)],
    )

    print("\n" + "=" * 70)
    print("STARTING TRAINING")
    print("=" * 70)
    if device == "cuda":
        print(f"  CUDA memory allocated before training: {torch.cuda.memory_allocated(0) / 1024**2:.2f} MB")
    print()

    trainer.train()

    print("\n" + "=" * 70)
    print("TRAINING COMPLETE - SAVING MODEL")
    print("=" * 70)
    output_dir.mkdir(parents=True, exist_ok=True)
    model.save_pretrained(output_dir)
    processor.save_pretrained(output_dir)
    print(f"\nModel saved to: {output_dir}")

    if args.eval_test and len(test_rows) > 0:
        print("\n" + "=" * 70)
        print("EVALUATING ON TEST SET")
        print("=" * 70)
        test_dataset = SyntheticMenuDataset(test_rows, dataset_dir, processor, split_name="test")
        test_results = trainer.evaluate(test_dataset)

        cer = test_results.get("eval_cer")
        wer = test_results.get("eval_wer")
        print("\nTest set results:")
        print(f"  CER: {cer:.4f}" if isinstance(cer, (int, float)) else f"  CER: {cer}")
        print(f"  WER: {wer:.4f}" if isinstance(wer, (int, float)) else f"  WER: {wer}")

    print("\n" + "=" * 70)
    print("NEXT STEPS")
    print("=" * 70)
    print(f"\n1. Point src/config.py at this model:\n")
    print("    @dataclass")
    print("    class RecognitionConfig:")
    print(f'        model_checkpoint: str = r"{output_dir.resolve()}"')
    print("\n2. Evaluate with real photos before production:")
    print(f"   python training/evaluate.py --out_dir <real_photos_dataset> --model {output_dir}")
    print("\nIMPORTANT: this model was trained on SYNTHETIC data only.")
    print("Performance on real handwritten menus may differ significantly -")
    print("validate with real examples before deploying.")
    print()


if __name__ == "__main__":
    main()